language: "sh"

sudo: "required"

services:
  - "docker"

dist: "trusty"

branches:
  only:
    - "master"

jobs:
  include:
    - env: "TASK=autoformat"
      env: "REPO_URL=git@github.com:wellcomecollection/terraform-aws-sqs.git"
    - env: "TASK=release"
      env: "REPO_URL=git@github.com:wellcomecollection/terraform-aws-sqs.git"
      stage: "release"

script:
  - python3 tf_tooling.py "$TASK"

stages:
  - "test"
  - name: release
    if: "type = push"
